feat/dispute-status-details: implemented change status endpoint
COS301-SE-2024/Dispute-Resolution-Engine pull request #200
Opened 2024-07-11 19:56 UTC by ZaguePrime

2024-07-16 19:49 UTC, Vafdaf12 commented
??

2024-07-17 19:06 UTC, vfeistel commented on api/handlers/dispute.go
> +	g.PUT("/dispute/status_change", h.updateStatus)
See #201

2024-07-17 19:08 UTC, vfeistel requested changes
See #201

2024-07-18 19:34 UTC, vfeistel approved these changes

2024-07-18 19:37 UTC, merged