Fixed the error being thrown when trying to create
COS301-SE-2024/Dispute-Resolution-Engine pull request #260
Opened 2024-07-24 11:15 UTC by ZaguePrime

Some stuff when sending the email was returned as an error response, I removed that code and made it log instead

2024-07-24 12:15 UTC, vfeistel commented on api/handlers/authentication.go
>  	}
This check handles the write to Redis on line 152. Please move it up and update the error message to reflect the error correctly

2024-07-24 12:16 UTC, vfeistel requested changes
check what's cooking

2024-07-25 17:13 UTC, vfeistel submitted a review, later dismissed

2024-07-25 17:13 UTC, vfeistel commented on api/handlers/authentication.go
>  		c.JSON(http.StatusInternalServerError, models.Response{Error: "Error generating token"})
What about the log messages?

2024-07-25 17:21 UTC, ZaguePrime commented on api/handlers/authentication.go
>  		c.JSON(http.StatusInternalServerError, models.Response{Error: "Error generating token"})
not sure what you're talking about

2024-07-26 10:56 UTC, CaelanHill approved these changes
lgtm

2024-07-26 10:57 UTC, merged